# Generated by Django 3.1 on 2020-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200902_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='project',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
