# Generated by Django 3.1 on 2020-09-11 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0004_auto_20200903_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
        migrations.RemoveField(
            model_name='address',
            name='project',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=500, verbose_name='Client')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('building_type', models.CharField(choices=[('OMU', 'Office-Mixed Use')], max_length=150, verbose_name='Building Type')),
                ('floors', models.IntegerField(verbose_name='Number of Fields')),
                ('task_target', models.CharField(choices=[('CO', 'Consumption Offset'), ('MS', 'Max Size')], max_length=50, verbose_name='Task Target')),
                ('consumption_overwrite', models.FloatField(verbose_name='Consumption Overwrite')),
                ('utility_overwrite', models.FloatField(verbose_name='Utility Overwrite')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Address')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
        ),
    ]
