# Generated by Django 3.1 on 2020-09-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200911_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.RemoveField(
            model_name='roof_info',
            name='address',
        ),
        migrations.AddField(
            model_name='roof_info',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_coordinates', to='address.project', verbose_name='Project'),
        ),
    ]
