# Generated by Django 3.1 on 2020-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_auto_20200915_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_type',
            field=models.CharField(blank=True, choices=[('OMU', 'Office-Mixed Use')], max_length=150, null=True, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consumption_overwrite',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumption Overwrite'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_target',
            field=models.CharField(blank=True, choices=[('CO', 'Consumption Offset'), ('MS', 'Max Size')], max_length=50, null=True, verbose_name='Task Target'),
        ),
        migrations.AlterField(
            model_name='project',
            name='utility_overwrite',
            field=models.FloatField(blank=True, null=True, verbose_name='Utility Overwrite'),
        ),
    ]
