# Generated by Django 3.1 on 2020-09-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_auto_20200915_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_image',
            field=models.ImageField(blank=True, null=True, upload_to='AddressImages/', verbose_name='Address Image'),
        ),
        migrations.CreateModel(
            name='Geocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=50, verbose_name='logitude')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Zipcode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_map_data', to='address.project', verbose_name='Project')),
            ],
        ),
    ]
