# Generated by Django 3.1 on 2020-09-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='row',
            field=models.IntegerField(default=0, verbose_name='Row in Dataframe'),
            preserve_default=False,
        ),
    ]
