# Generated by Django 3.1 on 2020-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_calculation_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterStringing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_manufacturer', models.CharField(max_length=150, verbose_name='Inverter Manufacturer')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('ac_size', models.FloatField(verbose_name='AC Size [kW]')),
                ('priority_rank', models.IntegerField(verbose_name='Priority Rank')),
                ('number_of_strings', models.IntegerField(verbose_name='Number of Strings')),
                ('module_manufacturer', models.CharField(max_length=150, verbose_name='Module Manufacter')),
                ('module_size', models.IntegerField(verbose_name='Module Size [W]')),
                ('module_per_string', models.IntegerField(verbose_name='Modules per String')),
                ('total_modules', models.IntegerField(verbose_name='Total Modules')),
                ('inverter_unit_cost', models.FloatField(verbose_name='Inverter Unit Cost [USD]')),
                ('module_cost_per_watt', models.FloatField(verbose_name='Module Cost [USD/W]')),
                ('optimizer_unit_price', models.FloatField(verbose_name='Optimizer Unit Price [USD]')),
                ('module_area_at_5_degree_tilt', models.FloatField(verbose_name='Module Area at 5° Tilt [sqf]')),
                ('module_degradation', models.CharField(max_length=50, verbose_name='Module Degradation [%/Year]')),
            ],
        ),
    ]
