# Generated by Django 3.1 on 2020-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_inverterstringing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterstringing',
            name='ac_size',
            field=models.FloatField(blank=True, null=True, verbose_name='AC Size [kW]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='inverter_manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Inverter Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='inverter_unit_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Inverter Unit Cost [USD]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_area_at_5_degree_tilt',
            field=models.FloatField(blank=True, null=True, verbose_name='Module Area at 5° Tilt [sqf]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_cost_per_watt',
            field=models.FloatField(blank=True, null=True, verbose_name='Module Cost [USD/W]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_degradation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Module Degradation [%/Year]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Module Manufacter'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_per_string',
            field=models.IntegerField(blank=True, null=True, verbose_name='Modules per String'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='module_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Module Size [W]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='number_of_strings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Strings'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='optimizer_unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Optimizer Unit Price [USD]'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='priority_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority Rank'),
        ),
        migrations.AlterField(
            model_name='inverterstringing',
            name='total_modules',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Modules'),
        ),
    ]
