# Generated by Django 3.1 on 2020-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_auto_20200929_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborBaseCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('category', models.CharField(max_length=150, verbose_name='Category')),
                ('cost', models.CharField(max_length=50, verbose_name='Cost')),
            ],
        ),
        migrations.CreateModel(
            name='LaborSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_size', models.IntegerField(verbose_name='Min Size [kW]')),
                ('max_size', models.IntegerField(verbose_name='Max Size [kW]')),
                ('adder', models.FloatField(verbose_name='Adder')),
            ],
        ),
        migrations.CreateModel(
            name='LaborState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='ST')),
                ('labor_adder_per_watt', models.CharField(max_length=50, verbose_name='Labor Adder [$/W]')),
                ('region', models.CharField(max_length=250, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLossesByST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='ST')),
                ('snow', models.CharField(max_length=50, verbose_name='Snow')),
                ('soiling', models.CharField(max_length=50, verbose_name='Soiling')),
                ('downtime', models.CharField(max_length=50, verbose_name='Downtime')),
                ('ac_losses', models.CharField(max_length=50, verbose_name='AC Losses')),
                ('shading', models.CharField(max_length=50, verbose_name='Shading')),
                ('total_losses', models.CharField(max_length=50, verbose_name='Total Losses [%]')),
            ],
        ),
    ]
